name: Connex Credit Activation Portal CI->CD

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
      - name: Build Docker Image
        run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Test Application
        run: |
          npm run test
      - name: Build Docker Image
        run: |
          npm run docker:build
      - name: Push Docker Image
        run: |
          npm run docker:push
      # - name: Deploy Application
      #   run: |
      #     npm run Heroku:ready
