name: Connex Credit Activation Portal CI->CD

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
        # test script running slow on github actions for some reason 🤷
      - name: Test Application
        run: |
          npm test
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          npm run docker:build
      - name: Push Docker Image
        run: |
          npm run docker:push
